name: geofas
favicon: null
layout_spectrum: 0.9816644671373069
typography_spectrum: 0.44212725409306586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7552062689792365
  lightness: 0.4361820083577186
  saturation: 0.3976814984343946
  rhythmicContrast: 0.1923289275728166
purpose: []
